FROM mysql
WORKDIR /var/lib/
RUN apt update
RUN apt install -y vim
ENV MYSQL_ROOT_PASSWORD=qwe123!@#
ENV MYSQL_DATABASE=mottex
ENV MYSQL_USER=mottex
ENV MYSQL_PASSWORD=bHLD4tJ7&$e%4L7
CMD ["--default-authentication-plugin=mysql_native_password"]