oncurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "mottex_dev_runner"
  url = "http://gitlab.mottex.ru/"
  token = "tfQ4nEA9DdpKS_nLUssr"
  executor = "shell"
#  builds_dir = "/home/mottex_ru/build"
  [runners.custom_build_dir]
#    enabled = true
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
